name : Hello 

on: 
  push:
    branches: [training]

jobs:
  hello: 
    runs-on: ubuntu-latest
    steps:
      - name: Hello 
        run: echo " Hello from Github Actions"
      
      - name: list the files
        run: ls -la
      
      - name: print the date
        run: date